#!/usr/bin/env python3
"""`docs/support-matrix.md`, printed from the SDK's own target declarations.

What capture a library gets is a property of the code that instruments it, so the table that tells a
customer what to expect is generated from that code and never written beside it: every row is one
`hajer._targets.Target`, and every cell is its `Support.row()`. A library that gains streaming support,
or loses a caveat, moves the table in the same commit as the change — and
`tests/test_support_matrix.py::test_matrix_matches_targets` fails if it did not.

Run it with the SDK's own interpreter, because it imports the SDK:

    uv run python scripts/generate_support_matrix.py --write
    uv run python scripts/generate_support_matrix.py --check
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from hajer._attach import targets
from hajer._targets import COLUMNS, Target

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "support-matrix.md"

_BANNER = (
    "<!-- Generated by python/scripts/generate_support_matrix.py from the `Target` declarations in\n"
    "     python/hajer/_attach.py. Do not edit: run the generator. -->"
)
_PREAMBLE = """# SDK support matrix

Which libraries `hajer.wrap(client)` and `hajer.attach()` instrument, and what each one's records
actually carry. Every row is generated from the SDK's own target declarations, so this table cannot
promise capture the code does not perform.

- **sync** / **async** — a synchronous client or function, and an `async` one, are both instrumented.
- **streaming** — a streamed call is recorded when the stream is exhausted or closed, never at garbage
  collection; `streamChunks` and `streamComplete` say what was observed.
- **usage available** — token counts are observable for this library, *including* for its streamed calls.
  A `no` is about the streamed path; a non-streamed call carries usage everywhere.
- **content captured** — message text, tool arguments and tool results can be recorded. On by default,
  for every library; `HAJER_CAPTURE_CONTENT=0` turns it off and keeps shapes, names, counts, timing and usage.
- **caveat** — what to know before trusting the row.
"""


def render(rows: Sequence[Target]) -> str:
    """The whole file, as text. One row per target, in declaration order."""
    head = f"| {' | '.join(COLUMNS)} |"
    rule = f"|{'---|' * len(COLUMNS)}"
    body = "\n".join(f"| {' | '.join(_cell(value) for value in target.support.row())} |" for target in rows)
    return f"{_BANNER}\n\n{_PREAMBLE}\n{head}\n{rule}\n{body}\n"


def _cell(value: str) -> str:
    """One cell: a pipe would end the column, so it is escaped rather than silently breaking the table."""
    return value.replace("|", "\\|")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write docs/support-matrix.md")
    parser.add_argument("--check", action="store_true", help="Exit 1 if the committed file is stale")
    parser.add_argument("--out", type=Path, default=OUT, help="Where to write (a temporary copy, for tests)")
    options = parser.parse_args(argv)
    rendered = render(targets())
    if options.check:
        current = options.out.read_text(encoding="utf-8") if options.out.exists() else ""
        if current != rendered:
            print(  # noqa: T201 - a generator reports to the operator who ran it
                f"{options.out.relative_to(ROOT)} is stale; run: "
                "uv run python scripts/generate_support_matrix.py --write",
                file=sys.stderr,
            )
            return 1
        print(f"generate_support_matrix: OK ({options.out.relative_to(ROOT)} is current)")  # noqa: T201
        return 0
    if not options.write:
        sys.stdout.write(rendered)
        return 0
    options.out.parent.mkdir(parents=True, exist_ok=True)
    options.out.write_text(rendered, encoding="utf-8")
    print(f"generate_support_matrix: wrote {options.out.relative_to(ROOT)}", file=sys.stderr)  # noqa: T201
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
