"""GENERATED by scripts/generate_wire.py — do not edit; run `just contract-refresh`.

Source: contract/openapi.json at sha256:43d82e5ec3d54b7c90deacb2d470cd41aaf3c9c9802aee63d3f311cf86dc38d2.

Every model below is the platform's own schema for one of the operations the SDK calls,
generated from the guarded snapshot. Hand-editing this file puts it permanently at odds
with its generator; `just contract-check` fails on any drift.
"""

from __future__ import annotations

from typing import Final, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field

from hajer._json import JsonValue

SNAPSHOT_DIGEST: Final[str] = "sha256:43d82e5ec3d54b7c90deacb2d470cd41aaf3c9c9802aee63d3f311cf86dc38d2"
SNAPSHOT_PATH: Final[str] = "contract/openapi.json"
OPERATIONS: Final[tuple[tuple[str, str], ...]] = (("post", "/api/teams/{team_id}/verify"), ("post", "/api/teams/{team_id}/observe"), ("get", "/api/teams/{team_id}/observations"), ("get", "/api/teams/{team_id}/observations/{observation_id}/assessment"), ("post", "/api/teams/{team_id}/projects/{project_id}/suite-runs/execution-inputs"),)
WIRE_READY: Final[bool] = True


CheckReason: TypeAlias = Literal["satisfied", "violated", "unsupported", "invalid", "not_applicable", "missing_evidence"]


ClaimedCaseKeySource: TypeAlias = Literal["CALLER", "DERIVED_CLIENT"]


IngestMode: TypeAlias = Literal["VERIFY", "OBSERVE"]


# components.schemas.JsonValue declares no shape of its own: it is the imported JsonValue.


MissingEvidenceReason: TypeAlias = Literal["ABSENT", "REDACTED", "TRUNCATED", "STALE", "INVALID"]


ObservedOrigin: TypeAlias = Literal["TARGET_SELF_REPORT", "BROKER"]


ProviderHost: TypeAlias = str


UnavailableReason: TypeAlias = Literal["SHADOW", "DEADLINE", "VERIFIER_UNKNOWN", "JUDGE_UNAVAILABLE", "BUDGET_EXHAUSTED", "INTERNAL"]


VerificationStatus: TypeAlias = Literal["satisfied", "violated", "insufficient_evidence", "unavailable"]


Wire: TypeAlias = Literal["OPENAI_CHAT_COMPLETIONS", "OPENAI_RESPONSES", "ANTHROPIC_MESSAGES"]


WorkflowHint: TypeAlias = str


class AssessmentOut(BaseModel):
    """What the SDK hands the application. A projection of the record, losing nothing it can act on."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    check_outcomes: tuple[VerificationCheckOutcomeOut, ...] = Field(alias="checkOutcomes")
    cost_microusd: int = Field(alias="costMicrousd")
    findings: tuple[VerificationFindingOut, ...]
    latency_ms: int = Field(alias="latencyMs")
    limitations: tuple[str, ...]
    missing_evidence: tuple[VerificationMissingEvidenceOut, ...] = Field(alias="missingEvidence")
    observation_id: str = Field(alias="observationId")
    seam: str | None
    shadow: bool
    status: VerificationStatus
    unavailable_reason: UnavailableReason | None = Field(alias="unavailableReason")
    verifier: str


class CallerFrameIn(BaseModel):
    """One application frame above the SDK on a captured call: where the call was made from."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    file: str | None = None
    file_digest: str | None = Field(None, alias="fileDigest")
    line: int | None = None
    module: str | None = None
    qualname: str | None = None


class ClientRedactionIn(BaseModel):
    """What the SDK removed before sending, as the client reported it."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    catalog: str
    counts_by_class: tuple[RedactionCountIn, ...] | None = Field(None, alias="countsByClass")
    degraded: str | None = None


class EvidenceStampIn(BaseModel):
    """What the caller alone knows about one evidence field: when it was observed, and how whole."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    completeness: Literal["COMPLETE", "PARTIAL", "MISSING", "UNKNOWN"] | None = None
    observed_at: str | None = Field(None, alias="observedAt")
    path: str


class ObservationRowOut(BaseModel):
    """One recorded observation, as a line in a tail. Compact on purpose: what arrived, not what it said."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    assessed: bool
    case_key: str | None = Field(alias="caseKey")
    case_key_source: str | None = Field(alias="caseKeySource")
    client_redactions: int = Field(alias="clientRedactions")
    created_at: str = Field(alias="createdAt")
    disposition: str
    id: str
    mode: IngestMode
    model: str | None
    origin: str
    provider: str | None
    raw_expires_at: str = Field(alias="rawExpiresAt")
    redacted_classes: tuple[str, ...] = Field(alias="redactedClasses")
    redactions: int
    shadow: bool
    verifier: str | None


class ObserveAcceptedOut(BaseModel):
    """The receipt for one flush: the id of every observation the server took, in the order sent."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    observation_ids: tuple[str, ...] = Field(alias="observationIds")
    state: Literal["accepted"]


class ObserveIn(BaseModel):
    """One ``observe`` flush: the observations the SDK's local queue batched, in the order it sent them."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    environment: str | None = None
    observations: tuple[VerifyIn, ...]


class PolledAssessmentOut(BaseModel):
    """The answer to ``GET /observations/{observation_id}/assessment``, whether or not there is one."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    check_outcomes: tuple[VerificationCheckOutcomeOut, ...] | None = Field(None, alias="checkOutcomes")
    cost_microusd: int | None = Field(None, alias="costMicrousd")
    findings: tuple[VerificationFindingOut, ...] | None = None
    judge_receipts: tuple[VerificationJudgeReceiptOut, ...] | None = Field(None, alias="judgeReceipts")
    latency_ms: int | None = Field(None, alias="latencyMs")
    limitations: tuple[str, ...] | None = None
    missing_evidence: tuple[VerificationMissingEvidenceOut, ...] | None = Field(None, alias="missingEvidence")
    observation_id: str = Field(alias="observationId")
    seam: str | None = None
    shadow: bool | None = None
    state: Literal["accepted", "assessed"]
    status: VerificationStatus | None = None
    unavailable_reason: UnavailableReason | None = Field(None, alias="unavailableReason")
    verifier: str | None = None


class PrivateSuiteInputsIn(BaseModel):
    """Generated from components.schemas.PrivateSuiteInputsIn."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    revision: str
    suite_digest: str = Field(alias="suiteDigest")
    suite_id: str = Field(alias="suiteId")
    suite_version: int = Field(alias="suiteVersion")


class PrivateSuiteInputsOut(BaseModel):
    """Generated from components.schemas.PrivateSuiteInputsOut."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    execution_document: str = Field(alias="executionDocument")
    revision: str
    unavailable_case_ids: tuple[str, ...] = Field(alias="unavailableCaseIds")


class RedactionCountIn(BaseModel):
    """How many values of one class the client removed. A count, never a value."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    category: str
    count: int


class SdkIdentityIn(BaseModel):
    """Which client sent this tuple. Recorded, because a wire bug is a client version."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    name: str
    version: str


class VerificationCheckOutcomeOut(BaseModel):
    """One check's own answer, kept underneath the aggregate status."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    check: str
    detail: str
    evidence_used: tuple[str, ...] = Field(alias="evidenceUsed")
    reason: CheckReason


class VerificationFindingOut(BaseModel):
    """A substantiated statement, naming the obligation it is about and the evidence it rests on."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    check: str
    evidence_used: tuple[str, ...] = Field(alias="evidenceUsed")
    obligation: str
    statement: str


class VerificationJudgeReceiptOut(BaseModel):
    """One judge call this assessment paid for: the lane, the route and what the ledger recorded."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    call_id: str = Field(alias="callId")
    cost_source: str = Field(alias="costSource")
    disposition: str
    lane: str
    latency_ms: int = Field(alias="latencyMs")
    model_id: str = Field(alias="modelId")
    reservation_microusd: int | None = Field(None, alias="reservationMicrousd")
    route_id: str = Field(alias="routeId")
    settled_microusd: int | None = Field(None, alias="settledMicrousd")


class VerificationMissingEvidenceOut(BaseModel):
    """One field the assessment needed and did not get, and which of the five reasons applies."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    detail: str
    field: str
    reason: MissingEvidenceReason


class VerifyIn(BaseModel):
    """One ``verify`` or ``observe`` submission — the wire form of ``VerifyEnvelope``."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    case_key: str | None = Field(None, alias="caseKey")
    case_key_source: ClaimedCaseKeySource | None = Field(None, alias="caseKeySource")
    client_redaction: ClientRedactionIn | None = Field(None, alias="clientRedaction")
    content_captured: bool | None = Field(None, alias="contentCaptured")
    deadline_ms: int | None = Field(None, alias="deadlineMs")
    environment: str | None = None
    evidence: dict[str, JsonValue] | None = None
    evidence_stamps: tuple[EvidenceStampIn, ...] | None = Field(None, alias="evidenceStamps")
    idempotency_key: str = Field(alias="idempotencyKey")
    mode: IngestMode
    origin: ObservedOrigin | None = None
    output: JsonValue
    request: dict[str, JsonValue]
    sdk: SdkIdentityIn
    verifier: str | None = None
    wrapped_calls: tuple[WrappedCallCaptureIn | WrappedCallSummaryIn, ...] | None = Field(None, alias="wrappedCalls")
    wrapped_calls_dropped: int | None = Field(None, alias="wrappedCallsDropped")


class WrappedCallCaptureIn(BaseModel):
    """One provider request/response pair, as bytes. This is the shape that becomes a receipt."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    caller_frames: tuple[CallerFrameIn, ...] | None = Field(None, alias="callerFrames")
    duration_ms: int = Field(alias="durationMs")
    reply_reads: tuple[str, ...] | None = Field(None, alias="replyReads")
    request: dict[str, JsonValue]
    response_body: str = Field(alias="responseBody")
    response_status: int = Field(alias="responseStatus")
    started_at: str = Field(alias="startedAt")
    streamed: bool | None = None
    truncated: bool | None = None
    wire: Wire
    workflow_hint: WorkflowHint | None = Field(None, alias="workflowHint")


class WrappedCallSummaryIn(BaseModel):
    """What ``hajer.wrap(client)`` records without the bytes: the call, described."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True, frozen=True)

    api: str
    caller_frames: tuple[CallerFrameIn, ...] | None = Field(None, alias="callerFrames")
    content: dict[str, JsonValue] | None = None
    declared_tools: tuple[str, ...] | None = Field(None, alias="declaredTools")
    duration_ms: int = Field(alias="durationMs")
    error: str | None = None
    error_type: str | None = Field(None, alias="errorType")
    finish_reason: str | None = Field(None, alias="finishReason")
    limitations: tuple[str, ...] | None = None
    message_count: int | None = Field(None, alias="messageCount")
    message_roles: tuple[str, ...] | None = Field(None, alias="messageRoles")
    model: str | None = None
    provider: str
    provider_host: ProviderHost | None = Field(None, alias="providerHost")
    request_settings: dict[str, JsonValue] | None = Field(None, alias="requestSettings")
    response_id: str | None = Field(None, alias="responseId")
    retries: int | None = None
    started_at: str = Field(alias="startedAt")
    stream_chunks: int | None = Field(None, alias="streamChunks")
    stream_complete: bool | None = Field(None, alias="streamComplete")
    streamed: bool | None = None
    tool_calls: tuple[dict[str, JsonValue], ...] | None = Field(None, alias="toolCalls")
    tool_results: tuple[dict[str, JsonValue], ...] | None = Field(None, alias="toolResults")
    usage: dict[str, int] | None = None
    workflow_hint: WorkflowHint | None = Field(None, alias="workflowHint")

AssessmentOut.model_rebuild()

CallerFrameIn.model_rebuild()

ClientRedactionIn.model_rebuild()

EvidenceStampIn.model_rebuild()

ObservationRowOut.model_rebuild()

ObserveAcceptedOut.model_rebuild()

ObserveIn.model_rebuild()

PolledAssessmentOut.model_rebuild()

PrivateSuiteInputsIn.model_rebuild()

PrivateSuiteInputsOut.model_rebuild()

RedactionCountIn.model_rebuild()

SdkIdentityIn.model_rebuild()

VerificationCheckOutcomeOut.model_rebuild()

VerificationFindingOut.model_rebuild()

VerificationJudgeReceiptOut.model_rebuild()

VerificationMissingEvidenceOut.model_rebuild()

VerifyIn.model_rebuild()

WrappedCallCaptureIn.model_rebuild()

WrappedCallSummaryIn.model_rebuild()
